autodft_flow:         
  mem: 256mb                                  # Memory (for 'chaperone' job)
  processors: 1                               # Number of processors (for 'chaperone' job)
  time: '30:00:00'                            # Wall time (for 'chaperone' job). Should be at least the sum of
                                              # wall times for the CREST and Gaussian jobs

crest:
  mem: 12gb                                   # Memory
  method: gfn2                                # Method
  nprocshared: 16                             # Number of processors
  rm_extra_files: true                        # Remove extra CREST files
  script: run_crest.sh                        # Script name
  solvent: ''                                 # Solvent (do not include --gbsa flag)
  time: '6:00:00'                             # Wall time
  keywords: ''                                # Additional keywords


gaussian_input:
  version: '16'                               # Version of Gaussian (09 or 16)
  maxjobs: 10                                 # Maximum number of jobs to submit
  mem: 12gb                                   # Memory per job
  nprocshared: 12                             # Processors per job
  script: run_gaussian.sh                     # Script name
  time: '24:00:00'                            # Wall time per job
  write_chk: false                            # Whether to write and keep .chk files. For linked jobs, .chk files
                                              # will always be written, but this decides whether they are kept

gaussian_jobs:                                # Dashes indicate beginning of data for a job (can add or remove jobs as desired)
- basisset: GENECP                            # Basis set
  ecp_basisset_heavy: SDD                     # For split basis sets, the basis set for heavy atoms
  ecp_basisset_light: 6-31G(d)                # For split basis sets, the basis set for light atoms
  ecp_cutoff: 36                              # For split basis sets, the maximum atomic number for light atoms
  functional: B3LYP                           # Functional
  route: Opt Freq SCF=XQC                     # Route line (for linked jobs, do not add geom=allcheck guess=read)
- basisset: def2TZVP
  ecp_basisset_heavy: null
  ecp_basisset_light: null
  ecp_cutoff: null
  functional: M062X
  route: ''


goodvibes:
  add_g_kcalmol: true                         # Add free energy in kcal/mol to the .csv file
  add_grel_kcalmol: true                      # Add free energy (relative) in kcal/mol to the .csv file
  conc: '1'                                   # Concentration (mol/L)
  f_cutoff: '100'                             # Frequency cutoff (cm-1)
  mark_lowest: true                           # Mark the lowest free energy structure in the .csv file
  qs: truhlar                                 # Quasiharmonic oscillator approximation method
  rename_lowest: true                         # Rename the .log file of the lowest free energy structure

